In [1]:
import numpy as np
from scipy import stats

# Семинар 8

## Задача 2

Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):

zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],

ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].

Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy

Полученные значения должны быть равны.

Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков, а затем с использованием функций из библиотек numpy и pandas.




In [2]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])


In [3]:
cov_manual = np.mean(zp*ks)-np.mean(zp)*np.mean(ks)
cov_manual

9157.839999999997

In [4]:
cov = np.cov(zp, ks, ddof=0)
cov

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [5]:
k_cov_pirson = cov/(np.std(zp, ddof=0)* np.std(ks, ddof=0))
k_cov_pirson

array([[0.33866702, 0.88749009],
       [0.88749009, 2.95275283]])

In [6]:
np.corrcoef(zp, ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

## Задача 2

Измерены значения IQ выборки студентов,

обучающихся в местных технических вузах:

131, 125, 115, 122, 131, 115, 107, 99, 125, 111.

Известно, что в генеральной совокупности IQ распределен нормально.

Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [7]:
data = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
alpha = 1-0.95
n = len(data)
alpha , n

(0.050000000000000044, 10)

In [8]:
std = np.std(data, ddof = 1)
std

10.54566788359614

In [9]:
M = np.mean(data)
M

118.1

In [10]:
T = stats.t.ppf( 1-alpha/2 ,n-1)
T

2.2621571627409915

In [11]:
# нижняя граница интервала
L = M - T *std/n**0.5

# верхняя граница интервала
U = M + T *std/n**0.5

print(f"Доверительный интервал  [{L:.2f};{U:.2f}]")

Доверительный интервал  [110.56;125.64]


## Задача 3

Известно, что рост футболистов в сборной распределен нормально с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27, среднее выборочное составляет 174.2. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [12]:
var = 25
M = 174.2
n = 27
alpha = 1-0.95 # Za/2 из таблицы = 1.96

In [13]:
# нижняя граница интервала
L = M - 1.96 *var**0.5/n**0.5

# верхняя граница интервала
U = M + 1.96 *var**0.5/n**0.5

print(f"Доверительный интервал для оценки математического ожидания [{L:.2f};{U:.2f}]")

Доверительный интервал для оценки математического ожидания [172.31;176.09]
